# .rubocop.yml — JetstreamBridge gem
# Focused for a Ruby gem: Packaging, Bundler, Rake, Performance, RSpec.

plugins:
  - rubocop-performance
  - rubocop-packaging

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2 # match gemspec minimum to avoid false positives
  SuggestExtensions: false
  Exclude:
    - "bin/*"
    - "pkg/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "spec/fixtures/**/*"

# ---------- Layout & Style ----------
Layout/LineLength:
  Max: 120
  Exclude:
    - "spec/**/*" # allow longer expectation/setup lines

Style/Documentation:
  Enabled: false # don’t force top-level docs for every class/module in a gem

Style/FrozenStringLiteralComment:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: single_quotes
  ConsistentQuotesInMultiline: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/HashSyntax:
  EnforcedShorthandSyntax: either

# ---------- Metrics (balanced for libs) ----------
Metrics/BlockLength:
  Max: 25
  Exclude:
    - "spec/**/*"
    - "Rakefile"
    - "tasks/**/*.rake"
    - "lib/jetstream_bridge/tasks/**/*.rake"
    - "jetstream_bridge.gemspec"
    - "lib/jetstream_bridge/core/connection.rb" # Connection validation logging blocks
    - "lib/jetstream_bridge/railtie.rb" # Rails initializer setup

Metrics/MethodLength:
  Max: 25
  Exclude:
    - "lib/jetstream_bridge/**/publisher*.rb"
    - "lib/jetstream_bridge/consumer/**/*.rb"
    - "lib/jetstream_bridge/core/debug_helper.rb"
    - "lib/jetstream_bridge/topology/stream.rb"
    - "lib/generators/jetstream_bridge/health_check/health_check_generator.rb"
    - "lib/jetstream_bridge/core/connection.rb" # Connection validation with logging
    - "lib/jetstream_bridge.rb" # Health check with performance metrics
    - "lib/jetstream_bridge/test_helpers/mock_nats.rb" # Mock NATS implementation

Metrics/AbcSize:
  Max: 25
  Exclude:
    - "lib/jetstream_bridge/**/publisher*.rb"
    - "lib/jetstream_bridge/consumer/**/*.rb"
    - "lib/jetstream_bridge/core/config.rb"
    - "lib/jetstream_bridge/core/debug_helper.rb"
    - "lib/jetstream_bridge/core/connection.rb" # Connection validation with logging
    - "lib/jetstream_bridge.rb" # Health check with performance metrics
    - "lib/jetstream_bridge/topology/stream.rb" # Stream update with compatibility checks

Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - "lib/jetstream_bridge/models/event.rb" # Hash-like [] accessor with many keys
    - "lib/jetstream_bridge/test_helpers.rb" # Test helper with complex setup
    - "lib/jetstream_bridge/core/logging.rb" # URL sanitization with multiple branches
    - "lib/jetstream_bridge/consumer/inbox/inbox_message.rb" # NATS message parsing
    - "lib/jetstream_bridge/consumer/inbox/inbox_processor.rb" # Inbox processing with multiple branches
    - "lib/jetstream_bridge/core/connection.rb" # Connection validation with multiple checks
    - "lib/jetstream_bridge/core/debug_helper.rb" # Stream info with compatibility checks
    - "lib/jetstream_bridge/test_helpers/mock_nats.rb" # Mock NATS implementation

Metrics/PerceivedComplexity:
  Max: 10
  Exclude:
    - "lib/jetstream_bridge/test_helpers.rb" # Test helper with complex setup
    - "lib/jetstream_bridge/core/logging.rb" # URL sanitization with multiple branches
    - "lib/jetstream_bridge/consumer/inbox/inbox_message.rb" # NATS message parsing
    - "lib/jetstream_bridge/core/connection.rb" # Connection validation with multiple checks
    - "lib/jetstream_bridge/core/debug_helper.rb" # Stream info with compatibility checks
    - "lib/jetstream_bridge/test_helpers/mock_nats.rb" # Mock NATS implementation

Metrics/ModuleLength:
  Max: 100
  Exclude:
    - "lib/jetstream_bridge.rb" # Main module with convenience methods
    - "lib/jetstream_bridge/core/debug_helper.rb" # Debug helper with stream info methods
    - "lib/jetstream_bridge/rails/integration.rb" # Rails integration with autostart logic

Metrics/ClassLength:
  Max: 200
  Exclude:
    - "lib/jetstream_bridge/core/connection.rb" # Connection validation adds significant logging
    - "lib/jetstream_bridge/consumer/consumer.rb" # Consumer with health checks and lifecycle

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: false # allow more keyword args for clarity
  Exclude:
    - "lib/jetstream_bridge/consumer/inbox/inbox_message.rb" # Internal message object with many fields

# ---------- Naming ----------
Naming/PredicateMethod:
  AllowedMethods:
    - validate!
    - validate_component!
    - publish_to_nats
    - wait_for_messages

Naming/PredicatePrefix:
  Enabled: true
  Exclude:
    - "lib/jetstream_bridge/test_helpers.rb" # RSpec matcher convention uses have_*
    - "lib/jetstream_bridge/test_helpers/matchers.rb" # RSpec matcher convention uses have_*
    - "lib/jetstream_bridge/core/model_utils.rb" # ActiveRecord introspection uses has_*
    - "lib/jetstream_bridge/models/outbox_event.rb" # ActiveRecord introspection uses has_*
    - "lib/jetstream_bridge/models/inbox_event.rb" # ActiveRecord introspection uses has_*

# ---------- Lint ----------
Lint/EmptyClass:
  Enabled: true
  Exclude:
    - "lib/jetstream_bridge/consumer/middleware.rb" # Forward declaration for circular dependency

Lint/EmptyBlock:
  Enabled: true
  Exclude:
    - "spec/**/*" # Empty blocks in tests are intentional for testing error handling

Lint/UnusedBlockArgument:
  Enabled: true
  Exclude:
    - "spec/**/*" # Test mocks may not use all arguments

Lint/UnusedMethodArgument:
  Enabled: true
  Exclude:
    - "lib/jetstream_bridge/test_helpers/mock_nats.rb" # Mock implementation compatibility

Lint/IneffectiveAccessModifier:
  Enabled: false # Allow class methods after private

Lint/UselessConstantScoping:
  Enabled: false

# ---------- Style ----------
Style/MultilineBlockChain:
  Exclude:
    - "spec/**/*" # allow chaining in tests for better readability

Style/OpenStructUse:
  Enabled: true
  Exclude:
    - "lib/jetstream_bridge/test_helpers.rb" # Test doubles for NATS messages
    - "lib/jetstream_bridge/test_helpers/integration_helpers.rb" # Test doubles for NATS messages
    - "lib/jetstream_bridge/test_helpers/mock_nats.rb" # Mock NATS message objects

# ---------- Packaging / Gemspec ----------
# These ship with RuboCop core and rubocop-packaging
Gemspec/RequiredRubyVersion:
  Enabled: true # aligns with your gemspec `required_ruby_version`

Gemspec/DevelopmentDependencies:
  Enabled: true

Packaging/BundlerSetupInTests:
  Enabled: true

Packaging/RequireRelativeHardcodingLib:
  Enabled: true

# ---------- Bundler ----------
Bundler/DuplicatedGem:
  Enabled: true

Bundler/InsecureProtocolSource:
  Enabled: true

Bundler/GemComment:
  Enabled: false

# ---------- Performance ----------
Performance/Detect:
  Enabled: true
Performance/RedundantMerge:
  Enabled: true
Performance/FixedSize:
  Enabled: true
