# .rubocop.yml — JetstreamBridge gem
# Focused for a Ruby gem: Packaging, Bundler, Rake, Performance, RSpec.

plugins:
  - rubocop-performance
  - rubocop-packaging

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2 # match gemspec minimum to avoid false positives
  SuggestExtensions: false
  Exclude:
    - "bin/*"
    - "pkg/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "spec/fixtures/**/*"

# ---------- Layout & Style ----------
Layout/LineLength:
  Max: 120
  Exclude:
    - "spec/**/*" # allow longer expectation/setup lines

Style/Documentation:
  Enabled: false # don’t force top-level docs for every class/module in a gem

Style/FrozenStringLiteralComment:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: single_quotes
  ConsistentQuotesInMultiline: true

Style/SymbolArray:
  EnforcedStyle: brackets

Style/HashSyntax:
  EnforcedShorthandSyntax: either

# ---------- Metrics (balanced for libs) ----------
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "Rakefile"
    - "tasks/**/*.rake"
    - "lib/jetstream_bridge/tasks/**/*.rake"
    - "jetstream_bridge.gemspec"

Metrics/MethodLength:
  Max: 25
  Exclude:
    - "lib/jetstream_bridge/**/publisher*.rb"
    - "lib/jetstream_bridge/consumer/**/*.rb"
    - "lib/jetstream_bridge/core/debug_helper.rb"
    - "lib/jetstream_bridge/topology/stream.rb"
    - "lib/generators/jetstream_bridge/health_check/health_check_generator.rb"

Metrics/AbcSize:
  Max: 25
  Exclude:
    - "lib/jetstream_bridge/**/publisher*.rb"
    - "lib/jetstream_bridge/consumer/**/*.rb"
    - "lib/jetstream_bridge/core/config.rb"
    - "lib/jetstream_bridge/core/debug_helper.rb"

Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - "lib/jetstream_bridge/models/event.rb" # Hash-like [] accessor with many keys
    - "lib/jetstream_bridge/test_helpers.rb" # Test helper with complex setup

Metrics/PerceivedComplexity:
  Max: 10
  Exclude:
    - "lib/jetstream_bridge/test_helpers.rb" # Test helper with complex setup

Metrics/ModuleLength:
  Max: 100
  Exclude:
    - "lib/jetstream_bridge.rb" # Main module with convenience methods

Metrics/ClassLength:
  Max: 200

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: false # allow more keyword args for clarity

# ---------- Naming ----------
Naming/PredicateMethod:
  AllowedMethods:
    - validate!
    - validate_component!
    - publish_to_nats

Naming/PredicatePrefix:
  Enabled: true
  Exclude:
    - "lib/jetstream_bridge/test_helpers.rb" # RSpec matcher convention uses have_*

# ---------- Lint ----------
Lint/EmptyClass:
  Enabled: true
  Exclude:
    - "lib/jetstream_bridge/consumer/middleware.rb" # Forward declaration for circular dependency

Lint/EmptyBlock:
  Enabled: true
  Exclude:
    - "spec/**/*" # Empty blocks in tests are intentional for testing error handling

Lint/UnusedBlockArgument:
  Enabled: true
  Exclude:
    - "spec/**/*" # Test mocks may not use all arguments

Lint/IneffectiveAccessModifier:
  Enabled: false # Allow class methods after private

Lint/UselessConstantScoping:
  Enabled: false

# ---------- Style ----------
Style/MultilineBlockChain:
  Exclude:
    - "spec/**/*" # allow chaining in tests for better readability

# Optional: relax just for low-level I/O integration code
# (you can delete this once you refactor)

# ---------- Packaging / Gemspec ----------
# These ship with RuboCop core and rubocop-packaging
Gemspec/RequiredRubyVersion:
  Enabled: true # aligns with your gemspec `required_ruby_version`

Gemspec/DevelopmentDependencies:
  Enabled: true

Packaging/BundlerSetupInTests:
  Enabled: true

Packaging/RequireRelativeHardcodingLib:
  Enabled: true

# ---------- Bundler ----------
Bundler/DuplicatedGem:
  Enabled: true

Bundler/InsecureProtocolSource:
  Enabled: true

Bundler/GemComment:
  Enabled: false

# ---------- Performance ----------
Performance/Detect:
  Enabled: true
Performance/RedundantMerge:
  Enabled: true
Performance/FixedSize:
  Enabled: true
