# .rubocop.yml — JetstreamBridge gem
# Ruby library optimized configuration with focus on:
# - Code quality and maintainability
# - Ruby gem packaging standards
# - Performance optimizations
# - Test readability

plugins:
  - rubocop-performance
  - rubocop-packaging

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  Exclude:
    - "bin/*"
    - "pkg/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "spec/fixtures/**/*"
    - "gemfiles/**/*"

# ---------- Layout & Style ----------
Layout/LineLength:
  Max: 120
  AllowedPatterns:
    - '\A\s*#'
  Exclude:
    - "spec/**/*"
    - "jetstream_bridge.gemspec"

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: aligned

Layout/HashAlignment:
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key
  EnforcedLastArgumentHashStyle: always_inspect

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/StringLiterals:
  EnforcedStyle: single_quotes
  ConsistentQuotesInMultiline: false

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Style/SymbolArray:
  EnforcedStyle: brackets
  MinSize: 3

Style/WordArray:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: either

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma

# ---------- Metrics ----------
# Balanced for library code - stricter than applications, but pragmatic
Metrics/BlockLength:
  Max: 25
  CountAsOne: ['array', 'hash', 'heredoc']
  Exclude:
    - "spec/**/*"
    - "Rakefile"
    - "tasks/**/*.rake"
    - "lib/jetstream_bridge/tasks/**/*.rake"
    - "jetstream_bridge.gemspec"
    - "lib/jetstream_bridge/core/connection.rb"
    - "lib/jetstream_bridge/railtie.rb"

Metrics/MethodLength:
  Max: 25
  CountAsOne: ['array', 'hash', 'heredoc']
  Exclude:
    - "lib/jetstream_bridge/**/publisher*.rb"
    - "lib/jetstream_bridge/consumer/**/*.rb"
    - "lib/jetstream_bridge/core/debug_helper.rb"
    - "lib/jetstream_bridge/topology/stream.rb"
    - "lib/generators/**/*"
    - "lib/jetstream_bridge/core/connection.rb"
    - "lib/jetstream_bridge.rb"
    - "lib/jetstream_bridge/test_helpers/mock_nats.rb"
    - "lib/jetstream_bridge/core/config.rb"
    - "lib/jetstream_bridge/core/connection_manager.rb"
    - "lib/jetstream_bridge/core/health_checker.rb"

Metrics/AbcSize:
  Max: 25
  CountRepeatedAttributes: false
  Exclude:
    - "lib/jetstream_bridge/**/publisher*.rb"
    - "lib/jetstream_bridge/consumer/**/*.rb"
    - "lib/jetstream_bridge/core/config.rb"
    - "lib/jetstream_bridge/core/debug_helper.rb"
    - "lib/jetstream_bridge/core/connection.rb"
    - "lib/jetstream_bridge.rb"
    - "lib/jetstream_bridge/topology/stream.rb"
    - "lib/jetstream_bridge/core/connection_manager.rb"

Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - "lib/jetstream_bridge/models/event.rb"
    - "lib/jetstream_bridge/test_helpers.rb"
    - "lib/jetstream_bridge/core/logging.rb"
    - "lib/jetstream_bridge/consumer/inbox/inbox_message.rb"
    - "lib/jetstream_bridge/consumer/inbox/inbox_processor.rb"
    - "lib/jetstream_bridge/core/connection.rb"
    - "lib/jetstream_bridge/core/debug_helper.rb"
    - "lib/jetstream_bridge/test_helpers/mock_nats.rb"
    - "lib/jetstream_bridge/core/config.rb"

Metrics/PerceivedComplexity:
  Max: 10
  Exclude:
    - "lib/jetstream_bridge/test_helpers.rb"
    - "lib/jetstream_bridge/core/logging.rb"
    - "lib/jetstream_bridge/consumer/inbox/inbox_message.rb"
    - "lib/jetstream_bridge/core/connection.rb"
    - "lib/jetstream_bridge/core/debug_helper.rb"
    - "lib/jetstream_bridge/test_helpers/mock_nats.rb"
    - "lib/jetstream_bridge/core/config.rb"

Metrics/ModuleLength:
  Max: 100
  CountAsOne: ['array', 'hash', 'heredoc']
  Exclude:
    - "lib/jetstream_bridge.rb"
    - "lib/jetstream_bridge/core/debug_helper.rb"
    - "lib/jetstream_bridge/rails/integration.rb"

Metrics/ClassLength:
  Max: 200
  CountAsOne: ['array', 'hash', 'heredoc']
  Exclude:
    - "lib/jetstream_bridge/core/connection.rb"
    - "lib/jetstream_bridge/consumer/consumer.rb"
    - "lib/jetstream_bridge/core/connection_manager.rb"

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: false
  Exclude:
    - "lib/jetstream_bridge/consumer/inbox/inbox_message.rb"

# ---------- Naming ----------
Naming/PredicateMethod:
  AllowedMethods:
    - validate!
    - validate_component!
    - publish_to_nats
    - wait_for_messages
    - check_health_if_due

Naming/PredicatePrefix:
  Enabled: true
  Exclude:
    - "lib/jetstream_bridge/test_helpers.rb" # RSpec matcher convention uses have_*
    - "lib/jetstream_bridge/test_helpers/matchers.rb" # RSpec matcher convention uses have_*
    - "lib/jetstream_bridge/core/model_utils.rb" # ActiveRecord introspection uses has_*
    - "lib/jetstream_bridge/models/outbox_event.rb" # ActiveRecord introspection uses has_*
    - "lib/jetstream_bridge/models/inbox_event.rb" # ActiveRecord introspection uses has_*

# ---------- Lint ----------
Lint/EmptyClass:
  Enabled: true
  Exclude:
    - "lib/jetstream_bridge/consumer/middleware.rb"

Lint/EmptyBlock:
  Enabled: true
  Exclude:
    - "spec/**/*"

Lint/UnusedBlockArgument:
  Enabled: true
  AllowUnusedKeywordArguments: true
  IgnoreEmptyBlocks: true
  Exclude:
    - "spec/**/*"

Lint/UnusedMethodArgument:
  Enabled: true
  AllowUnusedKeywordArguments: true
  Exclude:
    - "lib/jetstream_bridge/test_helpers/mock_nats.rb"

Lint/IneffectiveAccessModifier:
  Enabled: false

Lint/UselessConstantScoping:
  Enabled: false

Lint/MissingSuper:
  Enabled: true
  Exclude:
    - "lib/jetstream_bridge/errors.rb"
    - "lib/jetstream_bridge/test_helpers/**/*"

Lint/ConstantDefinitionInBlock:
  Enabled: true
  Exclude:
    - "spec/**/*"

# ---------- Style (Additional) ----------
Style/MultilineBlockChain:
  Exclude:
    - "spec/**/*"

Style/OpenStructUse:
  Enabled: true
  Exclude:
    - "lib/jetstream_bridge/test_helpers.rb"
    - "lib/jetstream_bridge/test_helpers/integration_helpers.rb"
    - "lib/jetstream_bridge/test_helpers/mock_nats.rb"

Style/ClassAndModuleChildren:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/AccessModifierDeclarations:
  Enabled: true
  EnforcedStyle: group

Style/GuardClause:
  Enabled: true
  MinBodyLength: 1

Style/ReturnNil:
  Enabled: false

Style/ReturnNilInPredicateMethodDefinition:
  Enabled: false

Style/SafeNavigation:
  Enabled: true
  ConvertCodeThatCanStartToReturnNil: true

# ---------- Packaging / Gemspec ----------
Gemspec/RequiredRubyVersion:
  Enabled: true

Gemspec/DevelopmentDependencies:
  Enabled: true

Gemspec/RequireMFA:
  Enabled: true

Gemspec/DeprecatedAttributeAssignment:
  Enabled: true

Packaging/BundlerSetupInTests:
  Enabled: true

Packaging/RequireRelativeHardcodingLib:
  Enabled: true

# ---------- Bundler ----------
Bundler/DuplicatedGem:
  Enabled: true

Bundler/InsecureProtocolSource:
  Enabled: true

Bundler/GemComment:
  Enabled: false

# ---------- Performance ----------
Performance/Detect:
  Enabled: true

Performance/RedundantMerge:
  Enabled: true

Performance/FixedSize:
  Enabled: true

Performance/StringInclude:
  Enabled: true

Performance/StartWith:
  Enabled: true

Performance/EndWith:
  Enabled: true

Performance/Casecmp:
  Enabled: true

Performance/RangeInclude:
  Enabled: true

Performance/UnfreezeString:
  Enabled: true

Performance/StringIdentifierArgument:
  Enabled: true
