# frozen_string_literal: true

source 'https://rubygems.org'

ruby '~> 3.2.0'

gem 'jetstream_bridge', path: '../../..'
gem 'pg', '~> 1.5'
gem 'puma', '~> 6.0'
gem 'rails', '~> 7.1.0'

group :development, :test do
  gem 'debug'
end
